[package]
name = "bin"
version = "0.1.0"
edition = "2018"
keywords = [
	"asciiart",
	"ascii-art",
	"ascii_art",
	"ascii-art-generator",
]
license = "MIT OR Apache-2.0"
readme = "../README.md"

[dependencies]
ascii-img2 = { version = "0.1.0", path = "../lib" }
clap = { version = "4.5.54", features = ["derive"] }
image = { version = "0.25.9", default-features = false, features = ["bmp", "gif", "jpeg", "png", "rayon", "tiff", "webp"] }
